name: Build, Publish, and Release .NET Core App

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # Trigger this workflow when you push a new tag starting with 'v', e.g., 'v1.0.0'

jobs:
  build-and-publish:
    name: Build and Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'
        dotnet-quality: 'preview'


    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --no-restore --output ./published

    # Double publish is needed for including build wwwroot folder files.
    - name: Publish
      run: dotnet publish --configuration Release --no-restore --output ./published

    - name: Upload published artifacts temporarily
      uses: actions/upload-artifact@v3
      with:
        name: published-${{ matrix.os }}
        path: ./published/

  create-release:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh

    - name: Create GitHub Release and upload artifacts
      run: |
        # Create a release
        gh release create ${{ github.ref }} \
          artifacts/*/* \
          --title "Release ${{ github.ref }}" \
          --repo ${{ github.repository }} \
          --notes "Release of ${{ github.ref }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

